# Generated by Django 6.0 on 2026-01-01 12:27

import django.db.models.deletion
import nanoid_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', nanoid_field.fields.NanoidField(alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, max_length=21, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('venue_type', models.CharField(choices=[('stadium', 'Stadium'), ('gymnasium', 'Gymnasium'), ('TRACK', 'Track'), ('FIELD', 'Field')], default='FIELD', max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('indoor', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
    ]
