# Generated by Django 6.0 on 2026-01-01 12:27

import django.db.models.deletion
import nanoid_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', nanoid_field.fields.NanoidField(alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, max_length=21, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', nanoid_field.fields.NanoidField(alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, max_length=21, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('score', models.JSONField(blank=True, help_text='Aggregate score summary', null=True)),
                ('athletes', models.ManyToManyField(blank=True, related_name='%(class)s_activities', to='people.athlete')),
                ('coaches', models.ManyToManyField(blank=True, related_name='%(class)s_activities', to='people.coach')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_activities', to='inventory.venue')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activities', to='scheduling.season')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', nanoid_field.fields.NanoidField(alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, max_length=21, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('focus', models.CharField(blank=True, help_text='Main focus of the training session', max_length=255)),
                ('athletes', models.ManyToManyField(blank=True, related_name='%(class)s_activities', to='people.athlete')),
                ('coaches', models.ManyToManyField(blank=True, related_name='%(class)s_activities', to='people.coach')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activities', to='scheduling.season')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_activities', to='inventory.venue')),
            ],
            options={
                'verbose_name': 'Training session',
                'verbose_name_plural': 'Training sessions',
                'ordering': ['-date'],
            },
        ),
    ]
